apiVersion: unfurl/v1alpha1
kind: Project
+?include-secrets: secrets/secrets.yaml
+?include-local: local/unfurl.yaml
default_environment: aws-staging


environments:
  defaults:
    connections:
      # declare the primary_provider as a connection to an Amazon Web Services account:
      primary_provider:
        type: unfurl.relationships.ConnectsTo.AWSAccount
        #  properties:
        #   AWS_DEFAULT_REGION: us-east1
        #   you should declare sensitive properties like this following in secrets/secrets.yaml or local/unfurl.yaml or define them as environment variables:
        #   AWS_ACCESS_KEY_ID:
        #   AWS_SECRET_ACCESS_KEY:
        #  For more properties see https://docs.unfurl.run/toscadef.html#unfurl-types

        # Alternatively, if you have already declared the connection in UNFURL_HOME you can rename the existing connection by
        # setting "primary_provider" to the name of the inherited connection, for example:
        # primary_provider: aws