apiVersion: unfurl/v1alpha1
kind: Project
# this file is including into unfurl.yaml but is listed in .gitignore
# so you can add configuration that you don't want committed to the repository,
# such as secrets, local settings, and local ensembles.
environments:
 defaults:
    # use "variables" to modify environment variables
    # keys are processed in order and a leader "+" and "-"
    # will copy or remove the variable from the environment
    # e.g.:
    # variables:
    #   -*:       # will remove all environment variables
    #   +HOME:    # will add HOME back
    #   FOO: bar  # set FOO
    variables: {}
    # make sure you keep this password in a safe place as this file isn't committed to the repository.
    secrets:
      vault_secrets:
        +%: merge # directive to merge this with other "vault_secrets" (by default secrets will be replaced)
        aws-staging7P: "uvMHs@uV^8qyqS"
      # Note: The UNFURL_VAULT_AWS-STAGING7P_PASSWORD environment variable overrides this.
    



